name: Release

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        arch:
          [
            aarch64,
            arm,
            armhf,
            i686,
            loongarch64,
            mips64el,
            mipsel,
            ppc,
            ppc64,
            ppc64le,
            riscv64,
            x86_64,
          ]

    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /opt/toolchains-res
          key: ${{ runner.os }}-cagent-${{ matrix.arch }}-${{ github.sha }}

      - name: Download toolchains
        run: |
          bash .github/download.sh

      - name: Install libprotobuf-c
        run: |
          export PLATFORM=$(echo $TOOLCHAIN_NAME | sed 's/-\(native\|cross\)//')
          wget https://github.com/protobuf-c/protobuf-c/releases/download/v1.5.0/protobuf-c-1.5.0.tar.gz
          tar -zxf protobuf-c-1.5.0.tar.gz
          cd ./protobuf-c-1.5.0
          ./configure --disable-shared --enable-static --disable-protoc --disable-largefile --prefix=/opt/toolchains/${TOOLCHAIN_NAME} --host=${PLATFORM}
          make -j${nproc}
          sudo PATH=$PATH make install

      - name: Build collector
        run: |
          git clone https://codeberg.org/uubulb/nz-collector
          cd nz-collector
          export VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          printf "%s" "$(git for-each-ref refs/tags/${VERSION} --format='%(contents)')" > body.txt
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../../cmake/${{ matrix.arch }}_musl.cmake -DENABLE_STATIC=1 ..
          make
          mv collector collector_${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nz-collector_${{ matrix.arch }}
          path: |
            ./nz-collector/build/collector_${{ matrix.arch }}

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./nz-collector/body.txt
          tag_name: ${{ env.VERSION }}
          files: |
            ./nz-collector/build/collector_${{ matrix.arch }}

      - name: Release to Codeberg
        uses: akkuman/gitea-release-action@v1
        with:
          name: ${{ env.VERSION }}
          body_path: ./nz-collector/body.txt
          server_url: https://codeberg.org
          repository: uubulb/nz-collector
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.GITEA_TOKEN }}
          files: |
            ./nz-collector/build/collector_${{ matrix.arch }}

      - name: Save toolchains
        if: always()
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            /opt/toolchains-res
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
